### ISSUE TITLE
KeyError: respBody 

### ISSUE THREAD

**Issue by secdevlpr26** [OSUSecLab/MiniCrawler#3]
I ran the main.py file and got the following error:

"Traceback (most recent call last):
  File "/home/supraja/1MiniApps/MiniApp-Crawler/MiniCrawler-main/MetadataCrawler/main.py", line 62, in <module>
    MiniAppsSearch._request_by_word(word, onitems)
  File "/home/supraja/1MiniApps/MiniApp-Crawler/MiniCrawler-main/MetadataCrawler/MiniAppsSearch.py", line 91, in _request_by_word
    _request_by_response(respjs, tdata, onitems)
  File "/home/supraja/1MiniApps/MiniApp-Crawler/MiniCrawler-main/MetadataCrawler/MiniAppsSearch.py", line 54, in _request_by_response
    while respjs['respBody']['continueFlag']:
KeyError: 'respBody' "

The following was the response from the API:
Response of request: b'{"base":{"session":{"_fake_id":"0","_sid_ticket":"","_data_ticket":"","_sid_expire":0,"_transkey":""},"ret":7}}'

I used Wechat version 8.0.18 [The latest version as of June 14] and used LSPosed-v1.8.3-6552-riru-release for the purpose.

And the following is my httpGetData.txt:

[wechatSearch getSearchSuggestionData] [version 80009162] [scene 201] [isHomePage 0] [type 262208] {"scene":201,"version":80009162,"query":"%%QUERY%%","type":262208,"isHomePage":0,"requestType":false,"sugId":"","sessionId":"-1538862360900281592"}

This is what I got from hooking the Wechat Search :)

I will be glad if you are able to help :))

**Comment by codingman-aiwass** [comment]
maybe you can install wechat 7.0.19 and have a try. And could you please tell me what phone and android version you have, I fail to get the content via adb logcat | grep WechatSearchToken on my Redmi Note11 android version 12. I wonder how to get this info. Thanks
